name: Android Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096M -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"

jobs:
  build-android:
    name: Build Android APK and Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Android RELEASE APK
        run: ./gradlew :composeApp:assembleRelease

      - name: Publish Release with APK
        uses: softprops/action-gh-release@v2
        with:
          files: composeApp/build/outputs/apk/release/composeApp-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}